import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fusion Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      variables: { colorPrimary: '#624cf5' }
    }}>
  <html lang="en">
      <body className={inter.className}>
      <NextTopLoader
          showSpinner={false}
          height={4}
          color="#B48CDE"
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
      <ToastContainer />
          {children}
      </body>
    </html>       
  </ClerkProvider>
  );
}
